export default {
	"storeId": 9203,
	"storeIdList": null,
	"id": 308158,
	"itemNo": "5875254410113816001",
	"storeId": 9203,
	"barcode": "WD015875254410118605",
	"name": "三角巾围脖",
	"categoryId": 5008066737,
	"labelId": null,
	"labelName": null,
	"brand": "",
	"categoryDTO": {
		"id": 5008066737,
		"parentId": null,
		"category": "周边产品",
		"categoryImgUrl": "https://prod-mall-cos-1252929494.cos.ap-guangzhou.myqcloud.com/fe5bafefa36c4c07b1b4e8c8bf4cb9f8z",
		"status": 1,
		"seq": 28,
		"isLeaf": 1,
		"industryId": 3,
		"name": null,
		"imgUrl": null,
		"imgUrlValue": null,
		"childrenCategory": [],
		"parentCategory": null,
		"outCategoryIdList": null
	},
	"salePrice": 4800,
	"labelPrice": 4800,
	"memberPrice": null,
	"itemSalesVolume": 5735,
	"virtualSalesVolume": 0,
	"isShelf": 1,
	"itemStock": 626,
	"itemWithholdStock": 0,
	"describe": "<p><img src=\"/static/images/mart/detail/baihuo_d_1.jpg\" style=\"max-width: 100%;\"><img src=\"/static/images/mart/detail/baihuo_d_2.jpg\" style=\"max-width: 100%;\"><img src=\"/static/images/mart/detail/baihuo_d_3.jpg\" style=\"max-width: 100%;\"><img src=\"/static/images/mart/detail/baihuo_d_4.jpg\" style=\"max-width: 100%;\"><img src=\"/static/images/mart/detail/baihuo_d_5.jpg\" style=\"max-width: 100%;\"><img src=\"/static/images/mart/detail/baihuo_d_6.jpg\" style=\"max-width: 100%;\"></p>",
	"status": 1,
	"thumbnail": "",
	"tag1": 0,
	"unit": "个",
	"paySubtractStock": false,
	"itemOrder": 0,
	"createTime": "2020-04-22 11:17:26",
	"updateTime": "2020-05-25 00:47:00",
	"costPrice": 0,
	"freight": 1200,
	"weight": 0,
	"placeOfOrigin": "",
	"shelfLife": null,
	"shelfLifeUnit": 0,
	"deliveryTimeType": 1,
	"deliveryTime": null,
	"daysAfterBuy": 1,
	"daysAfterBuyRange": "1-3",
	"preSellStartTime": null,
	"preSellEndTime": null,
	"freightTemplateId": 21,
	"invoiceTemplateId": null,
	"length": null,
	"width": null,
	"height": null,
	"volume": null,
	"subName": "有货",
	"peopleLimitAmount": null,
	"placeOfDispatch": "上海市",
	"shelfTime": "2020-05-23T02:04:50.000+0000",
	"preSell": false,
	"materialUrls": [
		"/static/images/mart/detail/baihuo_d_1.jpg",
		"/static/images/mart/detail/baihuo_d_2.jpg",
		"/static/images/mart/detail/baihuo_d_4.jpg",
	],
	"skuTreeList": [{
		"keyId": 116,
		"attrKeySort": 0,
		"keyName": "款式",
		"showImage": 0,
		"treeValList": [{
			"valId": 1709,
			"attrValSort": 4,
			"valName": "围脖",
			"imageId": null,
			"imageUrl": null
		}]
	}]
}
