export default [
    {
        "id": 1,
        "no": "755067202001181805428750",
        "outer_id": null,
        "pickup_no": "8191",
        "pickup_code_qrcode": "http://go.heytea.com/orders/755067202001181805428750/puckupNo",
        "pickup_type": "到店",
        "total_fee": "149.00",
        "box_fee": "0.00",
        "delivery_fee": "0.00",
        "discount_fee": "0.00",
        "coupon_fee": "0.00",
        "payment": "149.00",
        "currency_type": "CNY",
        "paid_at": "2022-03-31 21:05:50",
        "called_at": "2022-03-31 21:06:34",
        "status": "TRADE_CLOSED",
        "refund_status": "NO_REFUND",
        "reason": "协商一致退款",
        "pickup_time": "2022-03-31 18:49:32",
        "pickup_time_period": "",
        "pickup_time_period_show": null,
        "takeaway_time_immediately_show": "2022-03-31 21:50:50",
        "is_takeaway": false,
        "created_at": "2022-03-31 21:55:50",
        "remarks": "明天上午九点到店",
        "coupon_library_id": "",
        "activity": [],
        "is_comment": 2,
        "only_vip_show_invoice": false,
        "hidden_invoice": false,
        "invoice_successed": false,
        "show_remind_button": 0,
        "order_detail_qrcode": "https://go.heytea.com/device/755067202001181805428749/order",
        "making_order_count": 0,
        "need_wait_time": 0,
        "prior": 0,
        "trade_type": "JSAPI",
        "cupboard": null,
        "is_can_refund": false,
        "is_premade": false,
        "gather_feedback": false,
        "currency": 1,
        "tax_fee": "-1",
        "cancelCountdown": 0,
        "order_channel": "W",
        "open_pickupPage_expectTime": 1,
        "alipay_invoice_button": true,
        "new_order_invoice": true,
        "set_items": [],
        "showPaymentDetails": false,
        "items": [
            {
                "id": 1,
                "product_id": 551,
                "sku_id": 1420,
                "category_id": 11,
                "quantity": 2,
                "total_fee": "149",
                "price": "149",
                "name": "流心奶黄波波冰",
                "sname": "流心奶黄波波冰",
                "activity_name": "",
                "discount_price": 0,
                "show_trademark": false,
                "name_image": "",
                "activity_type": 0,
                "specifications": [],
                "attributes": [],
                "materials": [
                    {
                        "material_id": 140,
                        "name": "冰沙（推荐）",
                        "price": "0.00",
                        "material_group_id": 5
                    },
                    {
                        "material_id": 33,
                        "name": "少少冰",
                        "price": "0.00",
                        "material_group_id": 3
                    },
                    {
                        "material_id": 409,
                        "name": "常规吸管",
                        "price": "0.00",
                        "material_group_id": 27
                    },
                    {
                        "material_id": 68,
                        "name": "正常糖(推荐)",
                        "price": "0.00",
                        "material_group_id": 4
                    },
                    {
                        "material_id": 149,
                        "name": "标准（推荐）",
                        "price": "0.00",
                        "material_group_id": 6
                    }
                ],
                "image": "/static/images/order/phy_cat_1.jpg"
            }
        ],
        "shop": {
            "id": 308,
            "name": "正大广场萌宠一号店",
            "contact_phone": "0755-27906072",
            "contact_name": "萌宠",
            "province": "安徽省",
            "city": "芜湖市",
            "city_code": "156440300",
            "district": "弋江",
            "address": "九华南路189号",
            "latitude": "22.66992",
            "longitude": "113.827609",
            "min_charge": 30,
            "distance": 0,
            "delivery_distance": 3000,
            "support_mt_takeaway": 0,
            "support_sf_takeaway": 1,
            "support_td_takeaway": 0,
            "support_jd_takeaway": 0,
            "scene_code": "http://go.heytea.com/storage/shop/scene_code/shop_id_308.jpg",
            "tips": "15",
            "limit_cup": 50,
            "takeaway_limit_cup": "5",
            "location_city": null,
            "disable_order_type": 2,
            "country": "中国",
            "country_code": "156",
            "district_code": "440306",
            "support_cash": 1,
            "nearby_shop_count": 0,
            "is_current_city": null,
            "is_support_premade": 0,
            "currency": 1,
            "estimate_time_type": 1,
            "appointable": null
        },
        "delivery": null
    },
    {
        "id": 2,
        "no": "755067201911061936067635",
        "outer_id": null,
        "pickup_no": "8167",
        "pickup_code_qrcode": "http://go.heytea.com/orders/755067201911061936067635/puckupNo",
        "pickup_type": "到店",
        "total_fee": "488.00",
        "box_fee": "0.00",
        "delivery_fee": "0.00",
        "discount_fee": "0.00",
        "coupon_fee": "0.00",
        "payment": "10.00",
        "currency_type": "CNY",
        "paid_at": "2022-03-29 19:36:11",
        "called_at": "2022-03-29 19:38:16",
        "status": "TRADE_CLOSED",
        "refund_status": "NO_REFUND",
        "reason": "协商一致退款",
        "pickup_time": "2022-03-31 19:39:03",
        "pickup_time_period": "",
        "pickup_time_period_show": null,
        "takeaway_time_immediately_show": "2022-03-29 20:21:11",
        "is_takeaway": false,
        "created_at": "2022-03-31 19:40:06",
        "remarks": "明天下午三点到店",
        "coupon_library_id": "",
        "activity": [],
        "is_comment": 2,
        "only_vip_show_invoice": false,
        "hidden_invoice": false,
        "invoice_successed": false,
        "show_remind_button": 0,
        "order_detail_qrcode": "https://go.heytea.com/device/755067201911061936067635/order",
        "making_order_count": 0,
        "need_wait_time": 0,
        "prior": 0,
        "trade_type": "JSAPI",
        "cupboard": null,
        "is_can_refund": false,
        "is_premade": false,
        "gather_feedback": false,
        "currency": 1,
        "tax_fee": "1.15",
        "cancelCountdown": 0,
        "order_channel": "W",
        "open_pickupPage_expectTime": 1,
        "alipay_invoice_button": true,
        "new_order_invoice": false,
        "set_items": [],
        "showPaymentDetails": false,
        "items": [
            {
                "id": 106805414,
                "product_id": 161,
                "sku_id": 1186,
                "category_id": 20,
                "quantity": 1,
                "total_fee": "10.00",
                "price": "10.00",
                "name": "流沙牛角",
                "sname": "流沙牛角",
                "activity_name": "",
                "discount_price": 0,
                "show_trademark": false,
                "name_image": "",
                "activity_type": 0,
                "specifications": [],
                "attributes": [],
                "materials": [
                    {
                        "material_id": 41,
                        "name": "加热(推荐)",
                        "price": "0.00",
                        "material_group_id": 3
                    }
                ],
                "image": "/static/images/order/wash_hightLevel.jpg"
            }
        ],
        "shop": {
            "id": 308,
            "name": "正大广场萌宠一号店",
            "contact_phone": "0755-27906072",
            "contact_name": "萌宠",
            "province": "安徽省",
            "city": "芜湖市",
            "city_code": "241003",
            "district": "弋江区",
            "address": "新华富路77号1层L1-W55号",
            "latitude": "22.66992",
            "longitude": "113.827609",
            "min_charge": 30,
            "distance": 0,
            "delivery_distance": 3000,
            "support_mt_takeaway": 0,
            "support_sf_takeaway": 1,
            "support_td_takeaway": 0,
            "support_jd_takeaway": 0,
            "scene_code": "http://go.heytea.com/storage/shop/scene_code/shop_id_308.jpg",
            "tips": "15",
            "limit_cup": 50,
            "takeaway_limit_cup": "5",
            "location_city": null,
            "disable_order_type": 2,
            "country": "中国",
            "country_code": "156",
            "district_code": "440306",
            "support_cash": 1,
            "nearby_shop_count": 0,
            "is_current_city": null,
            "is_support_premade": 0,
            "currency": 1,
            "estimate_time_type": 1,
            "appointable": null
        },
        "delivery": null
    },
    {
        "id": 3,
        "no": "755067201911061932051221",
        "outer_id": null,
        "pickup_no": "8165",
        "pickup_code_qrcode": "http://go.heytea.com/orders/755067201911061932051221/puckupNo",
        "pickup_type": "到店",
        "total_fee": "99.00",
        "box_fee": "0.00",
        "delivery_fee": "0.00",
        "discount_fee": "0.00",
        "coupon_fee": "0.00",
        "payment": "99.00",
        "currency_type": "CNY",
        "paid_at": "2022-03-27 18:29:05",
        "called_at": "2022-03-27 18:29:35",
        "status": "TRADE_CLOSED",
        "refund_status": "NO_REFUND",
        "reason": "协商一致退款",
        "pickup_time": "2022-03-27 18:31:05",
        "pickup_time_period": "",
        "pickup_time_period_show": null,
        "takeaway_time_immediately_show": "2022-03-27 18:31:11",
        "is_takeaway": false,
        "created_at": "2022-03-27 18:32:05",
        "remarks": "明天上午九点到店",
        "coupon_library_id": "",
        "activity": [],
        "is_comment": 2,
        "only_vip_show_invoice": false,
        "hidden_invoice": false,
        "invoice_successed": false,
        "show_remind_button": 0,
        "order_detail_qrcode": "https://go.heytea.com/device/755067201911061932051221/order",
        "making_order_count": 0,
        "need_wait_time": 0,
        "prior": 0,
        "trade_type": "JSAPI",
        "cupboard": null,
        "is_can_refund": false,
        "is_premade": false,
        "gather_feedback": false,
        "currency": 1,
        "tax_fee": "1.58",
        "cancelCountdown": 0,
        "order_channel": "W",
        "open_pickupPage_expectTime": 1,
        "alipay_invoice_button": true,
        "new_order_invoice": false,
        "set_items": [],
        "showPaymentDetails": false,
        "items": [
            {
                "id": 106803531,
                "product_id": 660,
                "sku_id": 1590,
                "category_id": 12,
                "quantity": 1,
                "total_fee": "99.00",
                "price": "99.00",
                "name": "捣蛋南瓜波波冰",
                "sname": "捣蛋南瓜波波冰",
                "activity_name": "",
                "discount_price": 0,
                "show_trademark": false,
                "name_image": "",
                "activity_type": 0,
                "specifications": [],
                "attributes": [],
                "materials": [
                    {
                        "material_id": 409,
                        "name": "常规吸管",
                        "price": "0.00",
                        "material_group_id": 27
                    },
                    {
                        "material_id": 149,
                        "name": "标准（推荐）",
                        "price": "0.00",
                        "material_group_id": 6
                    },
                    {
                        "material_id": 140,
                        "name": "冰沙（推荐）",
                        "price": "0.00",
                        "material_group_id": 5
                    },
                    {
                        "material_id": 48,
                        "name": "少糖",
                        "price": "0.00",
                        "material_group_id": 4
                    },
                    {
                        "material_id": 558,
                        "name": "正常(推荐)",
                        "price": "0.00",
                        "material_group_id": 3
                    }
                ],
                "image": "/static/images/order/wash_cat.jpg"
            }
        ],
        "shop": {
            "id": 308,
            "name": "正大广场萌宠一号店",
            "contact_phone": "0755-27906072",
            "contact_name": "萌宠",
            "province": "安徽省",
            "city": "芜湖市",
            "city_code": "241003",
            "district": "弋江区",
            "address": "广深路福永段77号1层L1-W55号",
            "latitude": "22.66992",
            "longitude": "113.827609",
            "min_charge": 30,
            "distance": 0,
            "delivery_distance": 3000,
            "support_mt_takeaway": 0,
            "support_sf_takeaway": 1,
            "support_td_takeaway": 0,
            "support_jd_takeaway": 0,
            "scene_code": "http://go.heytea.com/storage/shop/scene_code/shop_id_308.jpg",
            "tips": "15",
            "limit_cup": 50,
            "takeaway_limit_cup": "5",
            "location_city": null,
            "disable_order_type": 2,
            "country": "中国",
            "country_code": "156",
            "district_code": "440306",
            "support_cash": 1,
            "nearby_shop_count": 0,
            "is_current_city": null,
            "is_support_premade": 0,
            "currency": 1,
            "estimate_time_type": 1,
            "appointable": null
        },
        "delivery": null
    },
    
]